### ISSUE TITLE
输出的csv文件用excel打开后是乱码

### ISSUE THREAD

**Issue by li2dd** [wuxingjie/redshoes-doc#2]
操作步骤：
1、创建流程，数据输出到csv文件
2、用excel打开该文件

期望结果：
输出数据与流程处理后的数据一致，数据无缺失

实际结果：
中文字符出现乱码

**Comment by DJLongZai** [comment]
excel程序默认使用的不是UTF-8编码。csv文件输出可以选择编码可以解决或调整excel打开csv文件默认编码。

**Comment by DJLongZai** [comment]
excel程序默认使用的不是UTF-8编码。csv文件输出可以选择编码可以解决或调整excel打开csv文件默认编码。

**Comment by wuxingjie** [comment]
这可能是office 2007特有的问题,其它例如wps或者文本编辑器打开都没问题
