### ISSUE TITLE
注册到系统服务

### ISSUE THREAD

**Issue by wuxingjie** [wuxingjie/redshoes-doc#4]
**遇到了什么问题,所以才需要(或者改进)这个功能?**
让用户不用每次运行start.bat,系统启动自动运行本系统

**如何解决这个问题?**
windows通过bat,linux通过sh
例如: install-service.bat install-service.sh

**有其他的替代方案吗?**
无

**附加信息**
无

**Comment by DJLongZai** [comment]
resolve

**Comment by wuxingjie** [comment]
目前zip,tar.gz这种绿色版使用apache common-daemon来启动和注册系统服务,面向服务器用户
exe,msi,rpm 使用jpackage打包,让桌面用户使用更便捷
