### ISSUE TITLE
引入vmoptions配置文件

### ISSUE THREAD

**Issue by wuxingjie** [wuxingjie/redshoes-doc#5]
**遇到了什么问题,所以才需要(或者改进)这个功能?**
让用户可以自定义vm参数

**如何解决这个问题?**
引入一个vmoptions配置文件,在启动时读取该配置文件拼接到java启动参数

**有其他的替代方案吗?**
无

**附加信息**
无

**Comment by DJLongZai** [comment]
resolve

**Comment by wuxingjie** [comment]
apache common-daemon读取vm.options文件
jpackage 读取打包后的cfg文件的[vm options]部分
