### ISSUE TITLE
对二进制进行分组报错

### ISSUE THREAD

**Issue by li2dd** [wuxingjie/redshoes-doc#6]
### 描述BUG
将content拖拽到分组字段，页面报错

### 重现
1、创建数据源：目录
2、添加数据处理：分组聚合
3、将content拖拽到分组字段

### 预期行为
无法拖拽二进制数据
![1655110559924](https://user-images.githubusercontent.com/107097996/173318197-b04e1365-d43f-4b2d-926f-51ed647e025c.jpg)

**Comment by DJLongZai** [comment]
解决：前端进行屏蔽类型为binary的数据
