### ISSUE TITLE
创建saphana数据源不应选择数据库名

### ISSUE THREAD

**Issue by li2dd** [wuxingjie/redshoes-doc#8]
### 描述BUG
创建saphana数据源不应选择数据库名

### 重现
1、创建数据源saphana

### 预期行为
创建saphana数据源应选择模式

### 其它信息
![image](https://user-images.githubusercontent.com/107097996/173514272-b421b487-1d98-4813-a986-e58a19c830c9.png)

**Comment by DJLongZai** [comment]
解决，此处应该只能选择：模式名
