### ISSUE TITLE
hive图标不展示

### ISSUE THREAD

**Issue by li2dd** [wuxingjie/redshoes-doc#9]
### 描述BUG
hive图标不展示

### 重现
1、创建数据源：hive
2、将hive拖拽至流程编辑页

### 预期行为
展示hive图标

### 其它信息
![image](https://user-images.githubusercontent.com/107097996/173529925-b1b78890-21e4-4e1b-b9f8-b37b3794dd46.png)

**Comment by DJLongZai** [comment]
打包文件未删除导致使用的是之前的图片
